version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - HTTP_LISTEN_ADDR=:8000
      - HTTP_CORS=http://localhost:3000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_WS_URI=http://localhost:8000/ws
    environment:
      - VITE_WS_URI=http://localhost:8000/ws
    ports:
      - "3000:3000"
    depends_on:
      - backend
